apiVersion: v1
data:
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_PATH: deployments_files/profile
  SERVER_PROFILE_URL: https://github.com/gmorgan-ping/license-as-secret.git
  SERVER_PROFILE_PARENT: GETTINGSTARTED
  SERVER_PROFILE_GETTINGSTARTED_PATH: getting-started/pingfederate
  SERVER_PROFILE_GETTINGSTARTED_URL: https://www.github.com/pingidentity/pingidentity-server-profiles.git
  
kind: ConfigMap
metadata:
  labels:
    role: pingfederate
  name: pingfederate-environment-variables